version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: hrdesk-postgres
    restart: always
    environment:
      POSTGRES_DB: hrdesk
      POSTGRES_USER: hrdesk
      POSTGRES_PASSWORD: hrdesk123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
